/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udemy.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import udemy.controller.BusinessException;
import udemy.controller.Service;
import udemy.model.Course;
import udemy.model.CoursesComboBoxModel;
import udemy.model.User;

/**
 *
 * @author Tarek
 */
public class Student extends javax.swing.JPanel {

    User user;
    public Student(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseNameLabel = new javax.swing.JLabel();
        enrollCourseButton = new javax.swing.JButton();
        coursesComboBox = new javax.swing.JComboBox<>();

        courseNameLabel.setText("course:");

        enrollCourseButton.setText("Enroll Course");
        enrollCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollCourseButtonActionPerformed(evt);
            }
        });

        coursesComboBox.setModel(new CoursesComboBoxModel(Service.getAllCourses()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseNameLabel)
                .addGap(63, 63, 63)
                .addComponent(coursesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(enrollCourseButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNameLabel)
                    .addComponent(enrollCourseButton)
                    .addComponent(coursesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enrollCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollCourseButtonActionPerformed
        // TODO add your handling code here:
        long courseId = ((Course)coursesComboBox.getSelectedItem()).getId();
        try {
            Service.enrollCourse(user.getId(), courseId);
            JOptionPane.showMessageDialog(this, "You have sucessfully enrolled in this course");
        } catch (BusinessException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_enrollCourseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JComboBox<Course> coursesComboBox;
    private javax.swing.JButton enrollCourseButton;
    // End of variables declaration//GEN-END:variables
}
